[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pde"
version = "0.1.0"
description = "PDE Foundation Model"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["pretrain*", "finetune*", "eval*", "tools*"]
